### ISSUE TITLE
Program Halt

### ISSUE THREAD

**Issue by JamesCourcelle** [cowboy8625/WordRPG#7]
Program halts when you create a character for the first time. This is may be due to the .db file that is created the first time this is ran. I was forced to terminate the program.

WORK AROUND: Close the terminal window and relaunch Main,py. Once this is completed, the game will move forward. Ideally, we should find a way to avoid this from occurrring.

**Comment by HexTree** [comment]
Haven't seen this, not sure how to recreate. Is it a regular occurrence for you?

**Comment by Djsurry** [comment]
me too. Havent been able to recreate, tried multiple times. What did you do leading up to the hang?

**Comment by voxelvortex** [comment]
You could add an option on the main screen to delete progress; This would delete the sql db file, and fix the bug. 
Kinda sub-optimal tho

**Comment by voxelvortex** [comment]
Update:
After cloning a fresh copy of the repo I had this problem too, restarting the game fixed the issue.

I tried to become an male assassin and it hung on a blank screen after a loading "page".

I'd imagine this is some sort of issue with first time set up, I'm making another clone of the repo as we speak, hopefully debug mode can shine some light on the issue.

**Comment by Djsurry** [comment]
following those steps I recreated it. If you leave it for like 20 minutes it goes on its one. Will investigate further

**Comment by HexTree** [comment]
Think this is fixed, since there is no db file generation any more.
